### ISSUE TITLE
Hardware acceleration with docker

### ISSUE THREAD

**Issue by irwinwilliams** [mayhewluke/react-native-docker#1]
Hey,
When I try to run the emulator, I get,

> ERROR: x86_64 emulation currently requires hardware acceleration

How'd you get past that?

**Comment by novaluke** [comment]
Hey @irwinwilliams !

Unfortunately it's been almost a year since I last used this, and I honestly don't remember how it works :(

On the one hand, you could try googling around for how to enable hardware acceleration for your platform (the [official Android developer docs on emulator acceleration](https://developer.android.com/studio/run/emulator-acceleration) might help, for example).

Alternatively it seems like you might be able to work around this by not using an `x86_64`-based image. For example, the readme on this repo suggests passing `--package 'system-images;android-23;default;x86_64'` to `avdmanager create avd`. You might have some luck trying to find an alternative to the `x86_64` part of that parameter.

I'm afraid those two wild guesses are the best I've got right now. If you do find out how to solve the issue, definitely let me know :) Good luck!
